#!/bin/bash
# This scriptr reads a list of filenames from a file and deletes matching files from the specified directories.
# Check if at least two arguments are provided
if [ "$#" -lt 2 ]; then
    echo "Usage: $0 file_list directory1 [directory2 ...]"
    exit 1
fi

file_list="$1"
shift  


if [ ! -f "$file_list" ]; then
    echo "The file list $file_list does not exist."
    exit 1
fi


while IFS= read -r filename || [ -n "$filename" ]; do
    for dir in "$@"; do
        if [ -d "$dir" ]; then
    
            find "$dir" -type f -name "$filename" -exec rm -f {} +
            echo "Deleted files named '$filename' in directory $dir"
        else
            echo "Directory $dir does not exist."
        fi
    done
done < "$file_list"


#include <stdio.h>
#define LENGTH 20
#define WIDTH  30


